[AUTHOR]
	ARACADERISE
[TITLE]
	Database Nodes
[DESCRIPTION]
	Database-Node in a C project that creates Database Nodes, or Databases that do specific tasks

[RUN]
	gcc -c main.c
	./main

[FILES]
	./main.c
	./CORE.c
	./CORE.h
