[AUTHOR]
	AUTHOR_NAME = "ARACADERISE"
[TITLE]
	TITLE_NAME = "Database Nodes"
[DESCRIPTION]
	DESCRIPTION_ = "Database-Node in a C project that creates Database Nodes, or Databases that do specific tasks"

[RUN]
	_ = "gcc -c main.c"
	COMPILER = "./main"

[FILES]
	MAIN_FILE = "./main.c"
	OTHERS = ["./CORE.c","./CORE.h","types.h","CORE_types.h"]
