[AUTHOR]
	AUTHOR_NAME = "ARACADERISE"
[TITLE]
	TITLE_NAME = "Database Nodes"
[DESCRIPTION]
	DESCRIPTION_ = "Database-Node is a C project that creates Database Nodes, or Databases that do specific tasks"

[RUN]
	_ = "gcc -c main.c"
	COMPILER = "./main"

[FILES]
	MAIN_FILE = "./main.c"
	OTHERS = [
		"./CORE.c",
		"./CORE.h",
		"./types.h",
		"./CORE_types.h",
		"./Python/DefaultNode.py",
		"./Python/dataparser.py",
		"./SetupEra.c",
		"./SetupEra.h",
		"./STORAGE.c",
		"./STORAGE.h"
	]
	GENERATED = [
		"EraData.json -> Python/dataparser.py",
		"CreateDefaultNode -> Generated -> CORE.c, Edited -> Python/dataparser.py",
		"NodeData.json -> Python/dataparser.py",
		"NodeInformation -> Generated -> CORE.c, Edited -> Python/dataparser.py"
	]
